import { Toaster } from "@/components/ui/sonner";
import { TRPCReactProvider } from "@/trpc/client";
import { ClerkProvider } from '@clerk/nextjs';
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Geist, Geist_Mono, Montserrat_Alternates } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserratAlternates = Montserrat_Alternates({
  variable: "--font-montserrat-alternates",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "FingAI.",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
     appearance={{
       variables: {
         colorPrimary: "#F83D93"
       }
     }}
    >
    <TRPCReactProvider>
        <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable}  ${geistMono.variable} ${montserratAlternates.variable} antialiased`}
      >
       <ThemeProvider attribute='class' defaultTheme="system" enableSystem disableTransitionOnChange>
         <Toaster/>
        {children}
       </ThemeProvider>
      </body>
    </html>
    </TRPCReactProvider>
    </ClerkProvider>
   
  );
}
